comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true

coverage:
  status:
    project:
      default:
        threshold: "1"
        informational: true

codecov:
  max_report_age: off
