name: Add label to opened issues
on:
  issues:
    types:
      - opened
permissions: {}
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const issue = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const originalLabels = issue.data.labels.map(l => l.name);
            const statusLabels = originalLabels.filter(l => l.startsWith("status: "));
            if (statusLabels.length === 0 && !originalLabels.includes("up-for-grabs")) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["status: new"]
              })
            }
